### PR TITLE
Fix #26 & should fix #31

### LINKED ISSUE #26: Reload data on re-join
I configured MySQL but it is not loading, I set the rank on a server but when I change servers the rank I set is not in my nickname/loaded

### LINKED ISSUE #31: Добавить нижний регистр
Команда по добавлению рангов работает не корректно если писать ник в нижнем регистре она не будет работать

### PR DESCRIPTION
**Pull request by xxAROX**
Changes:
 - The player's session will be removed on quit, so when he/she rejoin it will fetch roles again from db.

### CODE REVIEW

**Comment by IvanCraft623** [comment]
Thanks for the PR, however this solution will not be sufficient, the best alternative would be to reload the session data when the player re-logs in.

Your solution is to remove the session when the player exits the server, which will partially solve the problem, but if you load the data when the player is offline (for example using the `/ranks userinfo` command), the issue will still occur.

**Comment by xxAROX** [comment]
I fix it when I'm home, the function to reload session is Session->loadUserData() right?

**Comment by xxAROX** [comment]
Btw great job with this plugin 👍😁

**Comment by xxAROX** [comment]
@IvanCraft623 is this acceptable?

**Comment by xxAROX** [comment]
never mind this dosn't work

**Pull request closed without merging**
