### PR TITLE
remove useless command register code

### PR DESCRIPTION
**Pull request by Lunarelly**

### CODE REVIEW

**Comment by IvanCraft623** [comment]
I planned at some point to implement more commands, but never did.

**Comment by Lunarelly** [comment]
u can just return this if u ever want to add more, but at this point its useless

**Comment by IvanCraft623** [comment]
yeah, I don't think I would impmenet more commands, in any case I would add /ranksystem subcommands

**Comment by IvanCraft623** [comment]
Thank you for your PRs

**Pull request merged**
